services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend